development:
  adapter: postgresql
  encoding: unicode
  database: intra_development
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: postgresql
  encoding: unicode
  database: intra_test
  host: localhost
  pool: 5
  timeout: 5000
  encoding: utf8